### ISSUE TITLE
About Encoder

### ISSUE THREAD

**Issue by MichaelMai2000** [CrossTheRoadElec/FRC-Examples#1]
Hi! I am a team member from FRC5449 in China and I am confusing about the FeedBackDevice in CAN Talon SRX.
I am using Java and I always use my [digital encoder](http://www.andymark.com/product-p/am-3132.htm)(http://www.andymark.com/product-p/am-3132.htm) which has plugged into my roboRIO like this:
`Encoder Enc_r;
Enc_r = new Encoder(1,0);`

But in the example of CAN SRX PID, can I set my FeedBackDevice as a digital encoder?
How?

**Comment by ozrien** [comment]
The Encoder class is meant for quadrature encoders connected to the roboRIO's IO ports.

The CAN SRX PID is meant for sensors (such as quadrature encoders) connected to the Talon's feedback connector (See User Manual section 1.4.6).

**Comment by MichaelMai2000** [comment]
@ozrien 
I'm using E4T OEM Miniature Optical Encoder Kit (**am-3132**).
So now, If I want to connect Encoder and Talon, I should buy a TALON SRX / GADGETEER DATA CABLE (4-PACK)(or Talon SRX Data Cable, 6 in (am-2617)) and a **breakout board**.

There are 2 kinds of board, which breakout board shoud I buy?
Talon SRX Analog Breakout Board (am-2634)   or
Talon SRX Encoder Breakout Board (am-2633)
Thank you very much!

**Comment by ozrien** [comment]
The E4T is a quadrature sensor so you will want the am-2633...
(http://www.ctr-electronics.com/talon-srx-encoder-breakout-board.html)
