### ISSUE TITLE
Java and C++ examples needs updating from TalonSRXLib to CTRELib

### ISSUE THREAD

**Issue by sciencewhiz** [CrossTheRoadElec/FRC-Examples#3]

**Comment by JCaporuscio** [comment]
Can you elaborate?  The classes (and therefore the import statements and API) have not changed.  The only change when switching from TalonSRXLib to CTRLib was the name of the library file, which the WPILib plug-ins account for automatically.  Is there a specific issue you're having?

**Comment by sciencewhiz** [comment]
Sorry, with update 1 of the wpilib plugins, the old library wouldn't be deleted, which shows as a build path error. With update 2, the old library is removed automatically.
